# Generated by Django 6.0.4 on 2026-06-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
